version: '3.7'

services:

  sshtunnel:
    image: hjabbour/sshtunnel
    build: .
    container_name: sshtunnel
    volumes:
      - ./sshtunnel/data/:/data/:ro
    environment:
      - REMOTE=true
      - TUNNEL_HOST=haytham@homelab.rootit.top
      - TUNNEL_PORT=22
      - CONTAINER_HOST=npm_app_1
      - CONTAINER_PORT=80
      - REMOTE_PORT=5555
      - KEY=/data/keyfile
    restart: always
networks:
 default:
    external:
      name: npm_default
